
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-courses-w24-5pm-1
owner: ucsb-cs156-w24
repo_name: proj-courses-w24-5pm-1
pull_requests: [{"author":{"id":"U_kgDOBs097g","is_bot":false,"login":"haojustin","name":""},"headRefName":"UpdateCoursesByQuarterRangeJobForm","number":34,"title":"Update courses by quarter range job form","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-1/pull/34"},{"author":{"id":"MDQ6VXNlcjMwMDUzNTkx","is_bot":false,"login":"ChrisWoolson","name":"Chris Woolson"},"headRefName":"AddEditPage","number":33,"title":"Add edit page for personal schedules","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-1/pull/33"},{"author":{"id":"U_kgDOBXkTqQ","is_bot":false,"login":"El-Beetor","name":"Victor Garcia"},"headRefName":"vhg-DescriptiveError","number":31,"title":" FEATURE: More descriptive error message on personal schedule and Button! ","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-1/pull/31"}]
