
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-courses-w24-5pm-1
owner: ucsb-cs156-w24
repo_name: proj-courses-w24-5pm-1
pull_requests: [{"author":{"id":"U_kgDOBXkTqQ","is_bot":false,"login":"El-Beetor","name":"Victor Garcia"},"headRefName":"vhg-DescriptiveError","number":31,"title":" FEATURE: More descriptive error message on personal schedule and Button! ","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-1/pull/31"},{"author":{"id":"U_kgDOBXrZiw","is_bot":false,"login":"Bravo-Luis","name":"Luis Bravo"},"headRefName":"luis-deleteingAssociatedCourses","number":30,"title":"Associated Courses aren't deleted with Schedule","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-1/pull/30"},{"author":{"id":"U_kgDOBp4StA","is_bot":false,"login":"winzuo","name":""},"headRefName":"WZ-course-description","number":28,"title":"Added course description to course details page","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-1/pull/28"},{"author":{"id":"U_kgDOBXkTqQ","is_bot":false,"login":"El-Beetor","name":"Victor Garcia"},"headRefName":"vhg-RemoveExclam","number":27,"title":"UX: Remove unnecessary exclamation point","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-1/pull/27"},{"author":{"id":"U_kgDOB3BkNQ","is_bot":false,"login":"TantaiYanhen","name":"Sam Bian"},"headRefName":"Sam-developerPage","number":26,"title":"Add link to developer/GH info in Admin dropdown","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-1/pull/26"}]
